// src/lib/components/radio/Radio.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements';

  interface Props extends Omit<HTMLInputAttributes, 'type' | 'checked' | 'disabled'> {
    checked?: boolean;
    disabled?: boolean;

    onchange?: (event: Event) => void;
  }

  let {
    checked = $bindable(false),
    disabled = false,
    onchange,
    ...props
  }: Props = $props();

  function handleChange(event: Event) {
    checked = (event.currentTarget as HTMLInputElement).checked;
    onchange?.(event);
  }
</script>

<label
  class={[
    'radio',
    checked && 'radio--checked',
    disabled && 'radio--disabled'
  ].filter(Boolean).join(' ')}
>
  <input
    type="radio"
    class="radio__input"
    {checked}
    {disabled}
    onchange={handleChange}
    {...props}
  />

  <span class="radio__control" aria-hidden="true">
    <span class="radio__dot"></span>
  </span>
</label>

<style lang="scss" global>
  @use "./radio.scss";
</style>

// src/components/Radio/Radio.vue
<script setup lang="ts">
interface Props {
  id: string;
  name: string;
  value?: string;
  disabled?: boolean;
}

defineProps<Props>();

const model = defineModel<string>();
</script>

<template>
  <label :class="['radio', { 'radio--disabled': disabled }]" :for="id">
    <input
      :id="id"
      v-model="model"
      type="radio"
      :name="name"
      :value="value"
      :disabled="disabled"
      class="radio__input"
    />
    <span class="radio__dot" aria-hidden="true"></span>
    <span class="radio__label"><slot /></span>
  </label>
</template>

<style lang="scss">
@use './_radio.scss';
</style>
