// src/components/LoadingBar/LoadingBar.vue
<script setup lang="ts">
interface Props {
  type: 'known' | 'unknown';
  percentage?: number;
  width?: string;
}

defineProps<Props>();
</script>

<template>
  <div
    :class="['loading-bar', `loading-bar--${type}`]"
    :style="width ? { width } : undefined"
  >
    <div
      v-if="type === 'known' && percentage !== undefined"
      class="loading-bar__progress"
      :style="{ width: `${percentage}%` }"
    />
    <div v-else class="loading-bar__unknown" />
  </div>
</template>

<style lang="scss">
@use './_loadingBar.scss';
</style>

// src/lib/components/loadingbar/LoadingBar.svelte
<script lang="ts">
  interface Props {
    state?: 'unknown' | 'known';
    percentage?: number;
  }

  const {
    state = 'unknown',
    percentage,
    ...props
  }: Props = $props();
</script>

<div class={[`loadingbar`, !percentage && `loadingbar--${state}`].filter(Boolean).join(' ')} {...props}>
  <div class="loadingbar__background"></div>
  <div
    class="loadingbar__progress"
    style={percentage !== undefined ? `width: ${percentage}%` : undefined}
  ></div>
</div>

<style lang="scss" global>
  @use "./loadingbar.scss";
</style>
