// src/components/Notifications/Notification.vue
<script setup lang="ts">
import { ref } from 'vue';
import { X } from 'lucide-vue-next';

interface Props {
  type: 'info' | 'success' | 'warning' | 'error';
}

defineProps<Props>();

const emit = defineEmits<{ close: [] }>();

const visible = ref(true);

function close() {
  visible.value = false;
  emit('close');
}
</script>

<template>
  <div v-if="visible" :class="['notification', `notification__${type}`]" role="alert">
    <div :class="`notification__${type}__content`">
      <slot />
    </div>
    <button
      :class="`notification__${type}__close`"
      aria-label="Close notification"
      @click="close"
    >
      <X :size="16" />
    </button>
  </div>
</template>

<style lang="scss">
@use './_notification.scss';
</style>

// src/lib/components/notification/Notification.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import CloseIcon from '../icons/CloseIcon.svelte'; 

  let visible = $state(true);

  const fallbackMessageByType: Record<'error' | 'success' | 'warning' | 'info', string> = {
    error: 'Error message',
    success: 'Success message',
    info: 'Info message',
    warning: 'Warning Message',
  };

  interface Props {
    disabled?: boolean;
    type: "error" | "success" | "warning" | "info";

    children?: Snippet; 
  }

  const { type, children, ...props }: Props = $props();

  function handleClose() {
    visible = false;
  }
</script>

{#if visible}
  <div class={[`notification`, `notification--${type}`]} {...props}>
    {#if children}
      {@render children()}
    {:else}
      <span class="notification__message">{fallbackMessageByType[type]}</span>
    {/if}

    <button type="button" class="notification__close" aria-label="Close notification" onclick={handleClose}>
      <CloseIcon />
    </button>
  </div>
{/if}

<style lang="scss" global>
  @use "./notification.scss";
</style>
