// src/components/notification/Notification.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import Icon from '../icons/icon.svelte';


  interface Props {
    disabled?: boolean;
    type: "error" | "success" | "warning" | "info";

    children?: Snippet; 
  }

  const { type, children, ...props }: Props = $props();
</script>

<div class={[`notification`, `notification--${type}`]}
  {...props}>
  {#if children}
    {@render children()}
  {/if}
  <Icon type="close" size={24} />
</div>

<style lang="scss" global>
  @import "./notification.scss";
</style>

// src/components/Notifications/Notification.vue
<script setup lang="ts">
import { ref } from 'vue';
import { X } from 'lucide-vue-next';

interface Props {
  type: 'info' | 'success' | 'warning' | 'error';
}

defineProps<Props>();

const emit = defineEmits<{ close: [] }>();

const visible = ref(true);

function close() {
  visible.value = false;
  emit('close');
}
</script>

<template>
  <div v-if="visible" :class="['notification', `notification__${type}`]" role="alert">
    <div :class="`notification__${type}__content`">
      <slot />
    </div>
    <button
      :class="`notification__${type}__close`"
      aria-label="Close notification"
      @click="close"
    >
      <X :size="16" />
    </button>
  </div>
</template>

<style lang="scss">
@use './_notification.scss';
</style>
