// src/lib/components/checkbox/Checkbox.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLInputAttributes } from 'svelte/elements';

  interface Props extends Omit<HTMLInputAttributes, 'type' | 'checked' | 'disabled'> {
    checked?: boolean;
    disabled?: boolean;
    children?: Snippet;

    onchange?: (event: Event) => void;
  }

  let {
    checked = $bindable(false),
    disabled = false,
    children,
    onchange,
    ...props
  }: Props = $props();
</script>

<label
  class={[
    'checkbox',
    checked && 'checkbox--checked',
    disabled && 'checkbox--disabled',
    children && 'checkbox--with-label'
  ].filter(Boolean).join(' ')}
>
  <input
    type="checkbox"
    class="checkbox__input"
    bind:checked
    {disabled}
    {onchange}
    {...props}
  />

  <span class="checkbox__control" aria-hidden="true">
    <span class="checkbox__mark"></span>
  </span>

  {#if children}
    <span class="checkbox__label">
      {@render children()}
    </span>
  {/if}
</label>

<style lang="scss" global>
  @use "./checkbox.scss";
</style>

// src/components/Checkbox/Checkbox.vue
<script setup lang="ts">
interface Props {
  id: string;
  name?: string;
  disabled?: boolean;
}

defineProps<Props>();

const checked = defineModel<boolean>({ default: false });
</script>

<template>
  <label :class="['checkbox', { 'checkbox--disabled': disabled }]" :for="id">
    <input
      :id="id"
      v-model="checked"
      type="checkbox"
      :name="name"
      :disabled="disabled"
      class="checkbox__input"
    />
    <span class="checkbox__box" aria-hidden="true">
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="3"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <path d="M5 13l4 4L19 7"></path>
      </svg>
    </span>
    <span class="checkbox__label"><slot /></span>
  </label>
</template>

<style lang="scss">
@use './_checkbox.scss';
</style>
